<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="4" failures="0" skipped="0" tests="4" time="0.779" timestamp="2025-06-13T13:22:34.648008+02:00" hostname="rafa-thinkpad-dockstation"><testcase classname="" name="tests.unit.modules.test_hello_module" file="tests/unit/modules/test_hello_module.py" time="0.000"><error message="collection failure">/usr/lib/python3.12/site-packages/ansible_test/_util/target/pytest/plugins/ansible_pytest_collections.py:22: in collection_resolve_package_path
    raise Exception('File "%s" not found in collection path "%s".' % (path, ANSIBLE_COLLECTIONS_PATH))
E   Exception: File "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections/ansible_collections/sample_namespace/sample_collection/tests/unit/modules/test_hello_module.py" not found in collection path "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections:/home/rafsanch/.ansible/collections/ansible_collections".</error><error message="collection failure">/usr/lib/python3.12/site-packages/ansible_test/_util/target/pytest/plugins/ansible_pytest_collections.py:22: in collection_resolve_package_path
    raise Exception('File "%s" not found in collection path "%s".' % (path, ANSIBLE_COLLECTIONS_PATH))
E   Exception: File "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections/ansible_collections/sample_namespace/sample_collection/tests/unit/modules/test_hello_module.py" not found in collection path "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections:/home/rafsanch/.ansible/collections/ansible_collections".</error><error message="collection failure">/usr/lib/python3.12/site-packages/ansible_test/_util/target/pytest/plugins/ansible_pytest_collections.py:22: in collection_resolve_package_path
    raise Exception('File "%s" not found in collection path "%s".' % (path, ANSIBLE_COLLECTIONS_PATH))
E   Exception: File "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections/ansible_collections/sample_namespace/sample_collection/tests/unit/modules/test_hello_module.py" not found in collection path "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections:/home/rafsanch/.ansible/collections/ansible_collections".</error><error message="collection failure">/usr/lib/python3.12/site-packages/ansible_test/_util/target/pytest/plugins/ansible_pytest_collections.py:22: in collection_resolve_package_path
    raise Exception('File "%s" not found in collection path "%s".' % (path, ANSIBLE_COLLECTIONS_PATH))
E   Exception: File "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections/ansible_collections/sample_namespace/sample_collection/tests/unit/modules/test_hello_module.py" not found in collection path "/home/rafsanch/Documents/repos/ansible-devspaces-demo/collections:/home/rafsanch/.ansible/collections/ansible_collections".</error></testcase></testsuite></testsuites>